### ISSUE TITLE
Integração

### ISSUE THREAD

**Issue by lucax0** [GrupoZapVivaReal/crm-lead-integration#2]
Bom dia sou da equipe de desenvolvimento da SmartStaff,
 Gostaria de saber como funciona a integração e como deve ser gerado a url, se possivel direcionar a resposta ao email: lucas.uesato@smartstaff.com.br
                                                                                                          Obrigado desde já.

**Comment by renatoabec** [comment]
Oi Lucas, já entraremos em contato com você.
